name:                swf
version:             0.1.0.0
github:              "githubuser/swf"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/swf#readme>

dependencies:
- base >= 4.7 && < 5
- relude
- dotenv
- envy

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- TypeApplications
- RecordWildCards
- QuasiQuotes
- DeriveGeneric

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - warp
  - unliftio
  - scotty
  - http-types
  - blaze-html
  - postgresql-simple
  - postgresql-migration
  - resource-pool
  - monad-logger
  - wai-app-static
  - password
  - text-show
  - time
  - email-validate
  - validation-selective
  - clientsession
  - cereal
  - cereal-text
  - cryptohash-sha1
  - base16-bytestring
  - wreq
  - lens
  - aeson
  - http-client
  - wai-extra

executables:
  swf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - swf
  swf-dev:
    main:                Main.hs
    source-dirs:         dev
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - process
    - fsnotify
    - filepath
    - websockets
    - time
    - text-show

tests:
  swf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - swf
    - tasty
    - tasty-hspec
    - hspec
    - wreq
    - lens
